Repository OpenZeppelin/polkadot-runtime-templates, pull requests merged in 2024-02, with the labels that each got.

#78 Add documentation for `pallet_assets`
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/glossary.adoc
  docs/modules/ROOT/pages/pallets/assets.adoc
Labels: documentation

#113 Ci test
  .github/workflows/cargo-tests.yml
Labels: CI

#107 test runtime constants
  runtime/src/lib.rs
  runtime/src/xcm_config.rs
  runtime/tests/constants_test.rs
Labels: tests

#118 improve ci for space
  .github/workflows/cargo-tests.yml
Labels: CI

#120 remove redundant action
  .github/workflows/cargo-tests.yml
Labels: CI
